# Generated by Django 4.1.1 on 2022-10-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "idTipoUsuario",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("nombre", models.CharField(max_length=50)),
                ("correo", models.CharField(max_length=200)),
                ("clave", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=12)),
                ("idPersona", models.AutoField(primary_key=True, serialize=False)),
                (
                    "TipoUsuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud.tipousuario",
                    ),
                ),
            ],
        ),
    ]
